# Generated by Django 4.2.5 on 2024-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="vehicle_number",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
    ]
